### ISSUE TITLE
Code Rights

### ISSUE THREAD

**Issue by ldmario** [PeterStoyanov83/PONG#1]
I don't mind that you copy the code, but will be good to mention that. This code is from YouTube video. Changing the comments and adding few rows at the end doesn't make it yours :)

**Comment by PeterStoyanov83** [comment]
I apologise for this. I am new in coding and don't know much about the rights and licensing yet. Please write me what needs to be done/mentioned. Thank you and sorry one more time.

**Comment by ldmario** [comment]
There is no right for this code from my side. I rewrite this code from Youtube video to understand better how Turtle() module is working, perspective about things we can do with this module and practice of course. I wrote the issue because of the fact that you pretend like you wrote this code by yourself !

**Comment by PeterStoyanov83** [comment]
I apologise for this. I am new in coding and don't know much about the
rights and licensing yet. Please write me what needs to be done/mentioned.
Thank you and sorry one more time.
